### PR TITLE
Refactor SDK usage to repository

### LINKED ISSUE #19: Pass `limit` to SDK list methods
When calling `list()` methods on the SDK, we should pass the [`limit`](https://api.spinupwp.com/#pagination) parameter to ensure we're retrieving the maximum objects per API call. Currently, we're retrieving the default of 10 objects which makes the CLI feel sluggish when outputting long lists.

### PR DESCRIPTION
**Pull request by A5hleyRich**
Resolves #19

### CODE REVIEW

**Comment by A5hleyRich** [comment]
@danielmlozano could you review this, please?

**Review by danielmlozano — APPROVED** [review]
@A5hleyRich Looks and works well. My only question is, are we gonna use this new SpinupWRepository to include all the resources (servers, sites, logs, etc.) in the same class?

**Comment by A5hleyRich** [comment]
@danielmlozano that was the plan. I'm not sure the repository will have many other resources at this point but if it gets hard to manage we could extract the concerns to traits in the future. Forge does something similar: https://github.com/laravel/forge-sdk/blob/3.x/src/Forge.php#L10

**Comment by danielmlozano** [comment]
@A5hleyRich awesome! nice work. LGTM then.

**Pull request merged**
